"""Your migration message

Revision ID: 61a11309b375
Revises: 
Create Date: 2023-03-31 04:31:16.657547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a11309b375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('number_of_comments')
        batch_op.drop_column('number_of_likes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('number_of_followers')
        batch_op.drop_column('number_of_following')
        batch_op.drop_column('number_of_posts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_posts', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('number_of_following', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('number_of_followers', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_likes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('number_of_comments', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
