"""Your migration message

Revision ID: ef57d7422a5f
Revises: 61a11309b375
Create Date: 2023-04-01 11:46:44.980911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef57d7422a5f'
down_revision = '61a11309b375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_index('ix_comments_username')
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_user_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('followed_user_id', sa.String(), nullable=False))
        batch_op.drop_index('ix_follows_followed_username')
        batch_op.drop_index('ix_follows_follower_username')
        batch_op.create_index(batch_op.f('ix_follows_followed_user_id'), ['followed_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_user_id'), ['follower_user_id'], unique=False)
        batch_op.create_unique_constraint(None, ['follower_user_id', 'followed_user_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['followed_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['follower_user_id'], ['id'])
        batch_op.drop_column('follower_username')
        batch_op.drop_column('followed_username')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_index('ix_likes_username')
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_index('ix_posts_username')
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.create_index('ix_posts_username', ['username'], unique=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.create_index('ix_likes_username', ['username'], unique=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_username', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('follower_username', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['followed_username'], ['username'])
        batch_op.create_foreign_key(None, 'users', ['follower_username'], ['username'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_follows_follower_user_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followed_user_id'))
        batch_op.create_index('ix_follows_follower_username', ['follower_username'], unique=False)
        batch_op.create_index('ix_follows_followed_username', ['followed_username'], unique=False)
        batch_op.drop_column('followed_user_id')
        batch_op.drop_column('follower_user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.create_index('ix_comments_username', ['username'], unique=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
